from ui_functions.dataframes_saver import save_two_columns
from ui_functions.interpolador import interp_linea, interp_polilinea, interp_curva_bezier
from ui_functions.mallas_estructuradas_2D import interpolacion_transfinita_2D